[env]
term = "xterm-256color"

[keyboard]
bindings = [
    { key = "F", mods = "Shift|Control", action = "ReceiveChar" },
    { key = "B", mods = "Shift|Control", chars = "\u001b[66;6u" },
    { key = "O", mods = "Shift|Control", chars = "\u001b[79;6u" },
]

